apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: tracing  
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 4318
        - containerPort: 16686
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: tracing  
spec:
  selector:
    app: jaeger
  ports:
    - name: otlp
      port: 4318
      targetPort: 4318
    - name: ui
      port: 16686
      targetPort: 16686
