apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-customers-basic
  name: springboot-customers-basic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-customers-basic
  strategy: {}
  template:
    metadata:
      labels:
        app: springboot-customers-basic
    spec:
      containers:
        - image: adityasamantlearnings/springboot-customers-basic:0.0.5-SNAPSHOT
          name: springboot-customers-basic
          imagePullPolicy: Always
          env:
            - name: TRACING_URL
              value: "http://jaeger-collector.tracing.svc.cluster.local:14268/api/traces"
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-customers-basic
  name: springboot-customers-basic
spec:
  type: ClusterIP
  ports:
    - port: 8081
      name: web
      protocol: TCP
      targetPort: 8081
  selector:
    app: springboot-customers-basic

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-client-app
  name: springboot-client-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-client-app
  strategy: {}
  template:
    metadata:
      labels:
        app: springboot-client-app
    spec:
      containers:
        - image: adityasamantlearnings/springboot-client-app:0.0.4-SNAPSHOT
          name: client-app
          imagePullPolicy: Always
          env:
            - name: CUSTOMERS_BASIC_SERVICE_URL
              value: "http://springboot-customers-basic:8081"
            - name: TRACING_URL
              value: "http://jaeger-collector.tracing.svc.cluster.local:14268/api/traces"
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-client-app
  name: springboot-client-app
spec:
  ports:
    - port: 8082
      name: web
      protocol: TCP
      targetPort: 8082
  selector:
    app: springboot-client-app
  type: NodePort

