server:
    port: 8082
spring:
    application:
        name: client-app

customers:
    basic:
        service:
            url: http://localhost:8081
management:
    endpoint:
        health:
            probes:
                enabled: true
        prometheus:
            access: unrestricted
    endpoints:
        web:
            exposure:
                include: '*'
    info:
        git:
            mode: full

    tracing:
      sampling:
          probability: 1.0

tracing:
    url: http://localhost:4318/v1/traces

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"